name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@YOUR_EC2_IP << 'EOF'
            cd /home/ubuntu/your-app
            git pull origin main
            docker build -t your-app-image .
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:3000 your-app-image
          EOF
